### ISSUE TITLE
Use countryCode instead of country name

### ISSUE THREAD

**Issue by ashuvssut** [ivanoff/react-native-ico-flags#4]
instead of using country names like `<Icon name="india" />`

It would be nice if we could use countryCode instead. for example `<Icon name="IN" />` or `<Icon countryCode="india" />`

**Comment by angelxmoreno** [comment]
@ivanoff thoughts on this ?

**Comment by ivanoff** [comment]
Thank you for your suggestion.

From now on, you can use country codes instead of country names (react-native-ico-flags@3.4.1). If you need a reference for the country codes, you can visit the following link:

https://github.com/ivanoff/react-native-ico-flags/blob/master/src/synonyms

Best regards )

**Comment by amerllica** [comment]
@ivanoff, Does it work with the countries' names too?
